# Generated by Django 3.1.7 on 2021-03-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20210319_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
