# Generated by Django 3.1.7 on 2021-03-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipt_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='download',
            new_name='receipt_file',
        ),
    ]
