# Generated by Django 3.1.7 on 2021-03-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_auto_20210320_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='pdf',
            new_name='pdf_file',
        ),
    ]
